In [1]:
# module 임포트
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
plt.rcParams["figure.figsize"] = (14,8)

In [3]:
def plot_feature_importances(model, feature):
    n_features = len(feature)
    plt.barh(range(n_features), model.feature_importances_, align='center')
    plt.yticks(np.arange(n_features), feature)
    plt.xlabel("feature importances")
    plt.ylabel("feature index")
    plt.ylim(-1, n_features)

In [12]:
# dataset 로딩
x_load = pd.read_csv('C:\\Users\\zeus_\\Desktop\\champion_data\\train\\train_activity.csv').sort_values(by='acc_id', ascending=True)
y_load = pd.read_csv('C:\\Users\\zeus_\\Desktop\\champion_data\\train\\train_label.csv').sort_values(by='acc_id', ascending=True)

In [13]:
x_data = x_load
y_data = y_load

In [16]:
custom_filter = [v[0] or v[1] for v in zip(list((y_data.label == 'month').values), list((y_data.label == '2month').values))]

In [52]:
x_data = x_data.groupby('acc_id').sum().loc[custom_filter,:]

In [55]:
y_data = y_data.loc[custom_filter,:]

In [60]:
x_data['label'] = y_data.label.values

In [64]:
pd.crosstab(index=x_data[x_data.label == 'month'].normal_chat, columns='c')

col_0           c
normal_chat
-0.272301    2860
-0.268765      32
-0.265228     117
-0.265228       4
-0.261691       3
-0.261691       2
-0.261691      18
-0.258155       2
-0.258155       3
-0.258155       9
-0.258155       1
-0.254618       3
-0.254618       5
-0.254618       4
-0.251081       1
-0.251081       1
-0.251081       7
-0.251081       6
-0.247545       1
-0.247545       4
-0.247545       5
-0.247545       1
-0.247545       1
-0.244008       3
-0.244008       3
-0.244008       2
-0.244008       1
-0.244008       3
-0.240472       3
-0.240472       2
...           ...
 2.868233       1
 2.984942       1
 3.204214       1
 3.239580       1
 3.427022       1
 3.456624       1
 3.469461       1
 3.510572       1
 3.724978       1
 4.229838       1
 4.413744       1
 4.533989       1
 4.572892       1
 5.054754       1
 5.269610       1
 5.322659       1
 5.625482       1
 5.966328       1
 5.973401       1
 6.354908       1
 6.585239       1
 10.942377      1
 15.518786      1
 17.442717      1
 18.366658      1
 21.092527      1
 24.958072      1
 26.237006      1
 27.529207      1
 35.474254      1

[1917 rows x 1 columns]

In [65]:
pd.crosstab(index=x_data[x_data.label == '2month'].normal_chat, columns='c')

col_0           c
normal_chat
-0.272301    2261
-0.268765      35
-0.265228      39
-0.265228       4
-0.261691       7
-0.261691       7
-0.261691      11
-0.258155       4
-0.258155       6
-0.258155      16
-0.258155       2
-0.254618       4
-0.254618      13
-0.254618       6
-0.251081       2
-0.251081       4
-0.251081       7
-0.251081       1
-0.247545       2
-0.247545       1
-0.247545       3
-0.247545       7
-0.247545       1
-0.247545       3
-0.247545       1
-0.244008       2
-0.244008       4
-0.244008       4
-0.244008       3
-0.244008       1
...           ...
 3.091041       1
 3.122871       1
 3.122871       1
 3.136568       1
 3.200677       1
 3.603854       1
 3.932761       1
 4.282888       1
 4.392524       1
 4.420817       1
 4.438930       1
 4.509233       1
 4.529554       1
 4.572892       1
 4.601185       1
 4.682528       1
 4.769615       1
 4.947776       1
 5.471198       1
 6.571093       1
 6.910610       1
 6.999026       1
 7.927833       1
 8.434002       1
 8.774418       1
 10.113904      1
 12.196984      1
 15.186342      1
 37.583868      1
 41.628003      1

[1957 rows x 1 columns]

In [66]:
pd.crosstab(index=x_data[x_data.label == 'month'].whisper_chat, columns='c')

col_0           c
whisper_chat
-1.854616     729
-1.842293      11
-1.829970       3
-1.829970       7
-1.817647       6
-1.805325      15
-1.805325       1
-1.793002       5
-1.793002       7
-1.780679       3
-1.780679       4
-1.768356       1
-1.768356       4
-1.768356       2
-1.756034       5
-1.756034       6
-1.743711       3
-1.743711       5
-1.731388       2
-1.731388       4
-1.731388       3
-1.719066       2
-1.719066       4
-1.719066       5
-1.706743       1
-1.706743       2
-1.706743       5
-1.694420       3
-1.694420      16
-1.694420       1
...           ...
 19.192608      1
 20.116812      1
 20.252362      1
 21.679494      1
 21.694122      1
 21.866640      1
 23.400066      1
 23.961504      1
 24.577641      1
 24.762482      1
 25.243068      1
 26.007077      1
 27.880132      1
 27.941746      1
 30.320033      1
 30.763651      1
 31.848051      1
 32.476511      1
 34.226338      1
 34.522084      1
 34.953379      1
 43.579291      1
 44.577432      1
 50.295178      1
 51.586760      1
 52.661143      1
 54.866911      1
 58.290325      1
 65.846464      1
 80.313349      1

[2712 rows x 1 columns]

In [67]:
pd.crosstab(index=x_data[x_data.label == '2month'].whisper_chat, columns='c')

col_0            c
whisper_chat
-1.854616     1717
-1.842293       20
-1.842293        5
-1.829970       10
-1.829970       12
-1.817647        6
-1.817647       15
-1.805325       10
-1.805325        2
-1.793002        2
-1.793002        9
-1.780679        4
-1.780679        7
-1.768356        6
-1.768356        1
-1.756034        4
-1.756034        6
-1.743711        3
-1.743711        8
-1.731388        3
-1.731388       11
-1.719066        2
-1.719066        7
-1.719066        1
-1.706743        2
-1.706743        2
-1.706743        3
-1.694420        2
-1.694420        1
-1.694420        4
...            ...
 24.392800       1
 24.552995       1
 24.932695       1
 25.156809       1
 25.682076       1
 25.846882       1
 26.376759       1
 26.549277       1
 26.721796       1
 26.869668       1
 27.029864       1
 29.371183       1
 30.011965       1
 30.480228       1
 31.404433       1
 32.796902       1
 34.830152       1
 35.335384       1
 37.578121       1
 37.972448       1
 40.276799       1
 40.326090       1
 40.683449       1
 49.457233       1
 50.640215       1
 60.621626       1
 61.176149       1
 77.060148       1
 85.082246       1
 190.786625      1

[2197 rows x 1 columns]

In [69]:
pd.crosstab(index=x_data[x_data.label == 'month'].district_chat, columns='c')

col_0             c
district_chat
-0.132591      3654
-0.130663         9
-0.130663        37
-0.128736        10
-0.128736        13
-0.126808         7
-0.126808        18
-0.124881         1
-0.124881         1
-0.124881         4
-0.124881        10
-0.124881         1
-0.122953         1
-0.122953         1
-0.122953         3
-0.122953         3
-0.122953         3
-0.121026         1
-0.121026         1
-0.121026         1
-0.121026         3
-0.121026         4
-0.121026         2
-0.121026         5
-0.119098         1
-0.119098         4
-0.119098         1
-0.119098         3
-0.119098         1
-0.119098         1
...             ...
 0.862022         1
 0.894790         1
 0.973819         1
 0.977675         1
 0.987312         1
 1.001959         1
 1.080214         1
 1.220545         1
 1.361256         1
 1.361256         1
 1.478836         1
 1.497337         1
 1.565576         1
 1.594489         1
 1.646532         1
 1.663880         1
 1.845069         1
 1.972287         1
 2.015847         1
 2.064809         1
 2.272590         1
 2.333118         1
 2.348158         1
 2.438753         1
 2.558261         1
 2.569826         1
 3.074843         1
 3.375539         1
 4.212094         1
 7.292309         1

[544 rows x 1 columns]

In [68]:
pd.crosstab(index=x_data[x_data.label == '2month'].district_chat, columns='c')

col_0             c
district_chat
-0.132591      2729
-0.130663         9
-0.130663        59
-0.128736         2
-0.128736         9
-0.128736        21
-0.126808         5
-0.126808        30
-0.124881         1
-0.124881        10
-0.124881         9
-0.124881         8
-0.124881         6
-0.122953         2
-0.122953         4
-0.122953         2
-0.122953         4
-0.122953         9
-0.122953         3
-0.122953         4
-0.121026         1
-0.121026         1
-0.121026         7
-0.119098         1
-0.119098         1
-0.119098         1
-0.119098         2
-0.119098         1
-0.119098         1
-0.119098         5
...             ...
 0.952616         1
 0.979602         1
 1.001959         1
 1.060559         1
 1.074052         1
 1.104892         1
 1.151154         1
 1.153081         1
 1.160791         1
 1.164646         1
 1.195487         1
 1.201270         1
 1.203197         1
 1.253313         1
 1.301502         1
 1.320777         1
 1.328488         1
 1.360482         1
 1.388241         1
 1.546300         1
 1.586778         1
 1.739054         1
 1.821939         1
 1.831577         1
 2.064809         1
 2.419478         1
 2.704754         1
 3.219788         1
 4.081021         1
 5.730998         1

[700 rows x 1 columns]

In [71]:
pd.crosstab(index=x_data[x_data.label == 'month'].party_chat, columns='c')

col_0          c
party_chat
-2.201390   1348
-2.197070     20
-2.197070     13
-2.192749      1
-2.192749     16
-2.192749     25
-2.188428     16
-2.188428      2
-2.188428     24
-2.188428      6
-2.184108      5
-2.184108     21
-2.184108      7
-2.184108     30
-2.179787      1
-2.179787     22
-2.179787     29
-2.179787     13
-2.179787     23
-2.175467      2
-2.175467      2
-2.175467     42
-2.175467     22
-2.175467     24
-2.175467     17
-2.171146      4
-2.171146      9
-2.171146     16
-2.171146     60
-2.171146      9
...          ...
 21.000386     1
 21.454052     1
 21.691687     1
 22.629263     1
 22.715676     1
 23.147739     1
 23.242793     1
 24.543302     1
 24.793898     1
 25.087701     1
 25.433351     1
 27.034958     1
 28.349776     1
 28.721350     1
 29.689171     1
 30.324303     1
 31.784676     1
 32.069837     1
 34.315218     1
 35.042430     1
 35.085636     1
 37.323722     1
 37.656410     1
 39.004446     1
 41.160440     1
 42.085055     1
 43.182494     1
 45.848322     1
 50.276967     1
 58.067061     1

[2784 rows x 1 columns]

In [70]:
pd.crosstab(index=x_data[x_data.label == '2month'].party_chat, columns='c')

col_0           c
party_chat
-2.201390    1623
-2.197070       6
-2.197070       5
-2.192749       5
-2.192749       3
-2.188428       4
-2.188428       4
-2.188428       1
-2.184108       4
-2.184108       1
-2.179787       4
-2.179787       3
-2.179787       1
-2.179787       1
-2.175467       4
-2.175467       2
-2.175467       1
-2.175467       5
-2.171146       2
-2.171146       2
-2.171146      15
-2.171146       3
-2.171146       6
-2.171146       2
-2.166825       1
-2.166825       4
-2.166825      16
-2.166825      28
-2.166825       4
-2.166825       1
...           ...
 26.448699      1
 26.608562      1
 27.524536      1
 27.883148      1
 28.721350      1
 30.030500      1
 30.337265      1
 31.663698      1
 32.242662      1
 32.506221      1
 32.627198      1
 33.983876      1
 34.078930      1
 34.850976      1
 35.133163      1
 36.355901      1
 38.226733      1
 38.732247      1
 39.868572      1
 42.223315      1
 45.874246      1
 46.159408      1
 49.952920      1
 54.316755      1
 57.151087      1
 66.958915      1
 67.918094      1
 68.209204      1
 144.285208     1
 149.176160     1

[3017 rows x 1 columns]